---
- hosts: vm
  become: yes
  tasks:

  - name: Ensure directories exist
    file:
      path: /home/lab3885/ACIT3855Deployment
      state: directory

  - name: Pull latest code
    git:
      repo: 'git@github.com/Gautamd97/ACIT3855Deployment.git'
      dest: /home/lab3885/ACIT3855Deployment
      version: main

  - name: Copy production configs
    copy:
      src: ./prod-config/
      dest: /home/lab3885/ACIT3855Deployment/config/prod/
      mode: '0644'

  - name: Ensure volumes exist
    file:
      path: "{{ item }}"
      state: directory
    loop:
      - /home/lab3885/ACIT3855Deployment/data/kafka
      - /home/lab3885/ACIT3855Deployment/data/database
      - /home/lab3885/ACIT3855Deployment/data/processing

  - name: Start platform
    shell: docker compose up -d
    args:
      chdir: /home/lab3885/ACIT3855Deployment